### ISSUE TITLE
VoteReveal: Attempt to index a nil value

### ISSUE THREAD

**Issue by lnx00** [LewdDeveloper/lmaobox-scripting#1]
The script tries to access entities that are nil:
![Error](https://i.imgur.com/78xVjsL.png)

**Comment by LewdDeveloper** [comment]
fixed in 0e46935bf5c4080d60b6870bdf94c0e659ebf800 i guess?

**Comment by LewdDeveloper** [comment]
83209ae10596aa93addf58b7fea5992367431805 should totally fix the remaining issue
