### ISSUE TITLE
autovote.lua - prevent lua from voting yes on our lobby members

### ISSUE THREAD

**Issue by ghost** [LewdDeveloper/lmaobox-scripting#2]
lua ignores if 'target' is our lobby member and it votes against him. lobby member check can be implemeted using 
https://lmaobox.net/lua/Lua_Libraries/party/ through GetMembers()

**Comment by LewdDeveloper** [comment]
should be fixed in commit: 469431dc78ebfb2229581e7fa50e4909fa272cc1 #1
