### ISSUE TITLE
Unable to load any of the LUA's

### ISSUE THREAD

**Issue by ichigochantf2** [LewdDeveloper/lmaobox-scripting#4]
I have no idea if i am being dumb but i cannot seem to be able to launch your vote reveal.lua

I get this error in my games console

> C:\Users\user\AppData\Local\votereveal.lua:2: module 'json' not found:
	no field package.preload['json']
	no file 'json.lua'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\lua\json\init.lua'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\lua\json.lua'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\json\init.lua'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\json.lua'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\..\share\lua\)\5.4json\init.lua'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\..\share\lua\)\5.4.\json.lua'
	no file '.\json\init.lua'
	no file 'C:\Users\user\AppData\Local//json'
	no file 'C:\Users\user\AppData\Local//json.lua'
	no file 'C:\Users\user\AppData\Local//json//init.lua'
	no file 'json.dll'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\..\lib\lua\D:\SteamLibrary\steamapps\common\Team Fortress 2\)\json.dll'
	no file '5.4loadall.dll'
	no file 'D:\SteamLibrary\steamapps\common\Team Fortress 2\.\json.dll'

Any Help would be appreciated

**Comment by LewdDeveloper** [comment]
You'll need to download a file named dkjson.lua then move it to 
``'D:\SteamLibrary\steamapps\common\Team Fortress 2\json.lua'``
Here's the download link : http://dkolf.de/src/dkjson-lua.fsl/home
